# Generated by Django 4.2.4 on 2023-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userFullName',
            field=models.CharField(default='관리자', max_length=20),
        ),
    ]
