# Generated by Django 4.2.4 on 2023-08-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_userfullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userAge',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='userSex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=6),
        ),
    ]
