# Generated by Django 4.2.4 on 2023-08-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_userage_user_usersex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userAge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='userFullName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='userSex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6),
        ),
    ]
