# Generated by Django 4.2.4 on 2023-08-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_userage_alter_user_userfullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latestUpdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
