# Generated by Django 4.2.4 on 2023-08-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_latestupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userAge',
            field=models.IntegerField(default=0),
        ),
    ]
