# Generated by Django 4.2.4 on 2023-08-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='docImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
