# Generated by Django 4.2.4 on 2023-08-10 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalinfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagDate', models.DateField()),
                ('diagRegi', models.CharField(max_length=50)),
                ('diagNum', models.CharField(max_length=50)),
                ('diagMajor', models.CharField(max_length=100)),
                ('diagMajCode', models.CharField(max_length=100)),
                ('diagTF', models.BooleanField(default=False)),
                ('diagMinor', models.CharField(max_length=300)),
                ('diagMinCode', models.CharField(max_length=300)),
                ('diagInitDate', models.DateField()),
                ('diagMemo', models.TextField(default='')),
                ('diagIn', models.DateField()),
                ('diagOut', models.DateField()),
                ('diagUSage', models.CharField(blank=True, max_length=50, null=True)),
                ('diagETC', models.TextField(default='')),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalinfo.medi_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
