# Generated by Django 4.2.4 on 2023-08-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_diag_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diag_comment',
            name='comDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
