# Generated by Django 4.2.4 on 2023-08-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_diagnosis_diagdoc_alter_diagnosis_diaghospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagDocMaj',
            field=models.CharField(default='외과 전문의', max_length=50),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagDoc',
            field=models.CharField(default='김멋사', max_length=50),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagHospital',
            field=models.CharField(default='멋사 병원', max_length=50),
        ),
    ]
