# Generated by Django 4.2.4 on 2023-08-10 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalinfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prePharm', models.CharField(max_length=100)),
                ('preAddress', models.CharField(max_length=200)),
                ('preDate', models.DateField()),
                ('preChem', models.CharField(max_length=20)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('diag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis')),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalinfo.medi_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediName', models.CharField(max_length=100)),
                ('mediEffect', models.CharField(max_length=300)),
                ('mediDetail', models.CharField(max_length=100)),
                ('mediCode', models.CharField(max_length=100)),
                ('mediUnit', models.CharField(max_length=50)),
                ('mediAmount', models.CharField(max_length=50)),
                ('mediCount', models.CharField(max_length=50)),
                ('mediPeriod', models.CharField(max_length=50)),
                ('diag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis')),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalinfo.medi_info')),
                ('pre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
