# Generated by Django 4.2.4 on 2023-08-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_alter_pre_comment_comcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='prescription.pre_comment'),
        ),
    ]
