# Generated by Django 4.2.4 on 2023-08-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalinfo', '0006_alter_info_comment_comdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalinfo.info_comment'),
        ),
    ]
