# Generated by Django 4.2.4 on 2023-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalinfo', '0009_medi_info_hospital_medi_info_doc_medi_info_docmaj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caution',
            name='cauType',
        ),
        migrations.AddField(
            model_name='caution',
            name='cauIngName',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='caution',
            name='cauIngType',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='medi_info',
            name='patAge',
            field=models.IntegerField(default=0),
        ),
    ]
