# Generated by Django 4.2 on 2023-08-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalinfo', '0010_remove_caution_cautype_caution_cauingname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='guaPhone',
            field=models.CharField(default='010-1234-5678', max_length=13),
        ),
        migrations.AlterField(
            model_name='medi_info',
            name='patPhone',
            field=models.CharField(default='010-1234-5678', max_length=13),
        ),
    ]
