# Generated by Django 4.2.4 on 2023-08-10 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalinfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surChartNum', models.CharField(max_length=50)),
                ('surWriter', models.CharField(max_length=20)),
                ('surDate', models.DateField()),
                ('surNum', models.IntegerField()),
                ('surHospital', models.CharField(max_length=100)),
                ('surField', models.CharField(max_length=300)),
                ('surOper', models.CharField(max_length=20)),
                ('surAssi', models.CharField(max_length=20)),
                ('surAnesDoc', models.CharField(max_length=20)),
                ('surName', models.CharField(max_length=100)),
                ('surCode', models.CharField(max_length=50)),
                ('surPreDiag', models.CharField(max_length=100)),
                ('surPostDiag', models.CharField(max_length=100)),
                ('surAnes', models.CharField(max_length=100)),
                ('surEvent', models.BooleanField(default=False)),
                ('surRemoval', models.BooleanField(default=False)),
                ('surBloodTrans', models.BooleanField(default=False)),
                ('surPre', models.TextField(default='')),
                ('surDur', models.TextField(default='')),
                ('surPost', models.TextField(default='')),
                ('surTube', models.BooleanField(default=False)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('diag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis')),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalinfo.medi_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
