# Generated by Django 4.2.4 on 2023-08-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0005_sur_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='surDocMaj',
            field=models.CharField(default='외과 전문의', max_length=50),
        ),
    ]
