# Generated by Django 4.2.4 on 2023-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0006_surgery_surdocmaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='surCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surRegi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
